AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PowerUpdater: Eskom Loadshedding Telegram Bot

Globals:
  Function:
    Timeout: 40
    MemorySize: 128
    Runtime: python3.10
    Architectures:
        - arm64
    ReservedConcurrentExecutions: 1

Parameters:
    TelegramBotToken:
      Type: String
    TelegramChatID:
      Type: String

Resources:
  PowerUpdaterGetStageFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: power_updater/
      Handler: get_stage_lambda.lambda_handler
      Environment:
        Variables:
          PowerUpdaterTableName: !Ref PowerUpdaterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PowerUpdaterTable 
      Events:
        GetEskomStageEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *) #run every hour, on the hour at 0th minute

  PowerUpdaterGetScheduleFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: power_updater/
      Handler: get_schedule_lambda.lambda_handler
      Environment:
        Variables:
          PowerUpdaterTableName: !Ref PowerUpdaterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PowerUpdaterTable 
      Events:
        GetEskomScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1 3,7,11,15,19 * * ? *) #run 4 hourly, 1 minute past the hour, at specific hours  in GMT
  
  PowerUpdaterNotificationFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: power_updater/
      Handler: notification_lambda.lambda_handler
      Environment:
        Variables:
          PowerUpdaterTableName: !Ref PowerUpdaterTable
          PowerUpdaterGetScheduleFunction: !Ref PowerUpdaterGetScheduleFunction
          TelegramBotToken: !Ref TelegramBotToken
          TelegramChatID: !Ref TelegramChatID
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PowerUpdaterTable
      Events:
        Stream: #invoked when the stage changes, need to send telegram updates
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PowerUpdaterTable.StreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["MODIFY"]}'
        NotificationEvent:
          Type: Schedule
          Properties:
            Schedule: cron(2 3,7,11,15,19 * * ? *) #run 4 hourly, 2 minutes past the hour, at specific hours  in GMT

  PowerUpdaterTelegramHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: power_updater/
      Handler: telegramhandler_lambda.lambda_handler
      Environment:
        Variables:
          TelegramBotToken: !Ref TelegramBotToken
          TelegramChatID: !Ref TelegramChatID
          TelegramScheduleCommandStateMachine: !GetAtt TelegramScheduleCommandStateMachine.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PowerUpdaterTable
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt TelegramScheduleCommandStateMachine.Name
      Events:
        TelegramWebHook:
          Type: Api 
          Properties:
            Path: /
            Method: POST
  
  PowerUpdaterTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: area
          AttributeType: S
      KeySchema: 
        - AttributeName: area
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  TelegramScheduleCommandStateMachine:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: statemachine/telegram_command_schedule.asl.json
      DefinitionSubstitutions:
        PowerUpdaterGetStageFunctionArn: !GetAtt PowerUpdaterGetStageFunction.Arn
        PowerUpdaterGetScheduleFunctionArn: !GetAtt PowerUpdaterGetScheduleFunction.Arn
        PowerUpdaterNotificationFunctionArn: !GetAtt PowerUpdaterNotificationFunction.Arn
      Policies: 
      - LambdaInvokePolicy:
          FunctionName: !Ref PowerUpdaterGetStageFunction
      - LambdaInvokePolicy:
          FunctionName: !Ref PowerUpdaterGetScheduleFunction
      - LambdaInvokePolicy:
          FunctionName: !Ref PowerUpdaterNotificationFunction